# 项目端口号
port: 8005
# 服务器配置
data_base:
  # 服务器地址
  host: 127.0.0.1
  # 服务器端口
  port: 3306
  # 用户名
  user_name: root
  # 密码
  password: 071b956d-9b14-4bc3-8a59-a78ed16eb153
  # 数据库名
  schema: gin_co_store
# 日志配置
log_config:
  # 日志存储位置
  path: logs/
  # 日志名称
  name: run.logs
# 正则
regular:
  # 电话号码正则
  phone: ^(13[0-9]|14[5-9]|15[0-35-9]|16[6]|17[0-8]|18[0-9]|19[0-9]|147|166|17[0-1]|162)\d{8}$
  # 邮箱正则
  email: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$
# 邮箱配置
email_config:
  # 邮箱地址
  email_address: co-blog@qq.com
  # 邮箱名
  email_name: CoBlog站长
  # 邮箱密码
  password: qgiegwujfquqbjfd
  # 邮箱服务器
  smtp_server: smtp.qq.com
  # 邮箱端口
  smtp_port: 587
# redis
redis_config:
  host: 127.0.0.1
  port: 6379
  password: 6728d0b3-b77d-4783-896a-b8a6be7c87ad
  db: 2
# 加密
encryption:
  # 私钥
  private_key:
    password: d7aa251a-f619-48eb-8941-a3d9ca9d80b6
  # 盐值
  salt:
    password: 10
# token 配置
token:
  private_key: 6d6cae19-7bb8-4cfe-a445-bfc54532e342
# 不验证的接口地址
not_verify_url:
  - /test
  - /api/verifyCode/emailCode
  - /api/verifyCode/imgCode
  - /api/user/helloUser
  - /api/user/userNameOccupy
  - /api/user/phoneOccupy
  - /api/user/emailOccupy
  - /api/user/register
  - /api/user/phoneLogin
  - /api/user/emailLogin
  - /api/user/forgotPassword
  - /api/user/getUserNameByUid
  - /api/upload/userAvatar
  - /api/upload/productIcon
  - /api/product/getBannerList
  - /api/product/getProductList
  - /api/product/getProductInfo
  - /api/product/getProductType
  - /api/evaluate/getUserEvaluateList
  - /api/evaluate/getProductEvaluateList
# 跨域IP
cors:
  ip:
    - http://localhost
    - http://localhost:3001
    - http://localhost:4000
    - http://localhost:8001
    - http://127.0.0.1
    - http://127.0.0.1:3001
    - http://127.0.0.1:4000
    - http://127.0.0.1:8001
  methods:
    - GET
    - POST
    - PUT
    - DELETE
# 上传文件配置
upload:
  # 基础返回地址
  host: http://localhost:89/
  # 存储位置
  img_load:
    user: uploads/icon/ # 用户头像存储目录
    product: uploads/product/ # 商品图片存储目录
  # 文件大小
  max_size:
    # 图片
    img: 10
  # 可上传的类型
  img_type:
    - .jpg
    - .jpeg
    - .png
    - .bmp
    - .gif